[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration files
# file_template = %%(year)d%%(month).2d%%(day).2d_%%(rev)s_%%(slug)s
file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file
# timezone =

# sqlalchemy.url = driver://user:pass@localhost/dbname
# This is set in env.py from DATABASE_URL
sqlalchemy.url = DATABASE_URL

[post_write_hooks]
# post_write_hooks allows us to run scripts after a new migration file is created
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = REVISION_SCRIPT_FILENAME

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
