"use client";
import { useMemo, useState } from 'react';
export function SimulationPanel(){
  const [costPerGbYear, setCostPerGbYear] = useState(110);
  const [volumeGbDay, setVolumeGbDay] = useState(154);
  const [retentionDays, setRetentionDays] = useState(90);
  const [detectImprovePct, setDetectImprovePct] = useState(10);
  const current = useMemo(()=> volumeGbDay * 365 * costPerGbYear, [costPerGbYear, volumeGbDay]);
  const optimized = useMemo(()=> current * (1 - Math.min(0.6, (retentionDays < 90 ? 0.15 : 0.05) + detectImprovePct / 200)), [current, retentionDays, detectImprovePct]);
  const savings = Math.max(0, current - optimized);
  return <section className="rounded-2xl border border-white/15 bg-white/[0.04] p-5"><h3 className="text-base font-bold text-white">Simulation Panel</h3><p className="mt-1 text-sm text-white/65">Projected estimate only. Savings = Current Cost - Optimized Cost</p><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label className="text-sm text-white/80">Cost per GB/year<input type="number" value={costPerGbYear} onChange={(e)=>setCostPerGbYear(Number(e.target.value)||0)} className="mt-1 w-full rounded border border-white/20 bg-slate-900/60 px-2 py-1 text-white"/></label><label className="text-sm text-white/80">Daily ingest (GB)<input type="number" value={volumeGbDay} onChange={(e)=>setVolumeGbDay(Number(e.target.value)||0)} className="mt-1 w-full rounded border border-white/20 bg-slate-900/60 px-2 py-1 text-white"/></label><label className="text-sm text-white/80">Retention days<input type="range" min={30} max={365} value={retentionDays} onChange={(e)=>setRetentionDays(Number(e.target.value))} className="mt-2 w-full"/><span className="text-xs text-white/60">{retentionDays} days</span></label><label className="text-sm text-white/80">Detection improvement %<input type="range" min={0} max={50} value={detectImprovePct} onChange={(e)=>setDetectImprovePct(Number(e.target.value))} className="mt-2 w-full"/><span className="text-xs text-white/60">{detectImprovePct}%</span></label></div><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-lg border border-white/10 bg-slate-900/45 p-3"><p className="text-xs text-white/60">Projected Annual Spend</p><p className="text-xl font-bold text-white">${Math.round(optimized).toLocaleString()}</p></div><div className="rounded-lg border border-emerald-400/35 bg-emerald-500/10 p-3"><p className="text-xs text-white/60">Projected Savings</p><p className="text-xl font-bold text-emerald-200">${Math.round(savings).toLocaleString()}</p></div><div className="rounded-lg border border-blue-400/35 bg-blue-500/10 p-3"><p className="text-xs text-white/60">Confidence</p><p className="text-xl font-bold text-blue-100">{Math.max(70, 95 - Math.round(detectImprovePct / 2))}%</p></div></div></section>;
}
